---
language: python
python: 3.8.2

services:
  - docker

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install -r requirements.txt
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - black --check .
  - isort --check-only
  - MOLECULE_PYTHON=$(which python) molecule test
